sudo: required
services:
  - docker
before_install:
  - docker build -t jojoshuajosh/react-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jojoshuajosh/react-client-test npm test -- --coverage

after_success:
  - docker build -t jojoshuajosh/complex-client ./client
  - docker build -t jojoshuajosh/complex-nginx -f ./nginx/Dockerfile.dev ./nginx
  - docker build -t jojoshuajosh/complex-server ./server
  - docker build -t jojoshuajosh/complex-worker ./worker

  # Login into docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # push images to docker hub
  - docker push jojoshuajosh/complex-client
  - docker push jojoshuajosh/complex-nginx
  - docker push jojoshuajosh/complex-server
  - docker push jojoshuajosh/complex-worker