sudo: required
services:
  - docker 

before_install:
  - docker build -t jojoshuajosh/multi-react1 -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jojoshuajosh/multi-react1 npm run test -- --coverage --watchAll=false
  #- docker run jojoshuajosh/multi-react1 npm test -- --coverage
       
after_succes:
  - docker build -t jojoshuajosh/multi_client ./client
  - docker build -t jojoshuajosh/multi_nginx ./nginx
  - docker build -t jojoshuajosh/multi_server ./server
  - docker build -t jojoshuajosh/multi_worker ./worker

  
  # login to docker cli 123
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin    
  #take those images and push them to docker hub
  - docker push jojoshuajosh/multi_client 
  - docker push jojoshuajosh/multi_nginx 
  - docker push jojoshuajosh/multi_server 
  - docker push jojoshuajosh/multi_worker